config/routes.rb
Rails.application.routes.draw do
  get 'flats/index'
  get 'flats/new'
  get 'flats/edit'
  get 'flats/show'
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :flats
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/flat.rb
class Flat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/flats_controller.rb
class FlatsController < ApplicationController
  def index
    @flats = Flat.all
  end

  def new
    @flat = Flat.new
  end

  def create
    Flat.create(flat_params)
    redirect_to flats_path
  end

  def edit
    @flat = Flat.find(params[:id])
  end

  def update
    Flat.update(flat_params)
    redirect_to flats_index_path
  end

  def show
    @flat = Flat.find(params[:id])
  end

  private

  def flat_params
    params.require(:flat).permit(:name, :address, :description,
                                 :number_of_guests, :price_per_night)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/flats_helper.rb
module FlatsHelper
end

app/views/flats/edit.html.erb
<h1>Edit Flat</h1>
<%= simple_form_for [@flat] do |f| %>
  <%= f.input name %>
  <%= f.input address %>
  <%= f.input description %>
  <%= f.input number_of_guests %>
  <%= f.input price_per_night %>
  <%= fi.input 'Update Flat' %>
<% end %>
<%= link_to "Cancel", flat_path(params[:id]) %>

app/views/flats/index.html.erb
<%= link_to 'Simple Airbnb', flats_index_path %>

<!-- Search form goes here-->

<%= link_to 'Add Flat', flats_new_path %>
<h1>All Our Flats</h1>
<p>All <%= @flats.count %></p>

<ul>
  <% @flats.each do |flat| %>
  <br>
    <ul>
      <li><%= flat.name %> </li>
      <li><%= flat.details %></li>
      <div class="details">
        <li><%= flat.number_of_guests %></li>
        <li><%= flat.price_per_night %></li>
      </div>
      <div class="buttons">
        <li><%= link_to 'More info', flat_path(flat) %></li>
        <li><%= link_to 'Edit', edit_flat_path(flat) %></li>
        <li><%= link_to 'Remove', flat_path(flat), method: :delete %></li>
      </div>
    </ul>
  <% end %>
</ul>

app/views/flats/new.html.erb
<h1>Add a new flat</h1>
<%= simple_form_for [@flat] do |f| %>
  <%= f.input name %>
  <%= f.input address %>
  <%= f.input description %>
  <%= f.input number_of_guests %>
  <%= f.input price_per_night %>
  <%= fi.input 'Update Flat' %>
<% end %>
<%= link_to "Cancel", flat_path(params[:id]) %>

app/views/flats/show.html.erb
<div class="container">
  <div>
    <h1><%= @flat.name %></h1>
    <p><%= @flat.details %></p>
  </div>
  <h3><%= @flat.address %></h3>
</div>

<div class="container">
  <div>
    <!-- Form to book between two days -->
  </div>
  <div>
    <h3>Details</h3>
    <div>
      <%= @flat.number_of_guests %>
      <%= @flat.price_per_night %>
    </div>
  </div>
  <div>
    <p>Share</p>
    <!-- font awesome social media links -->
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsSimpleAirbnb</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>